-- Rule 209, made safe to write. A former handle keeps resolving even after
-- it has been reused — and nothing anywhere reserves a handle a rename
-- vacates, so reuse is ordinary rather than contrived: renaming A to B,
-- then B back to A, then A to B again writes three events under two
-- former handles, one of them twice; a handle vacated by one thing and
-- later claimed and renamed away by a different thing writes two events
-- under the same former handle for two different badges. The primary key
-- on `former_handle` alone allowed exactly one event per former handle,
-- ever — the second write in either sequence hit a duplicate-key error.
--
-- `ordinal` is this table's own per-key sequence, the same shape
-- `field_write` and `fact_stands_for` already keep: the primary key moves
-- to (former_handle, ordinal) in the two migrations after this one, so
-- every event is kept, and a lookup reads the highest ordinal for a
-- former handle to get the newest one — the same newest-write-wins rule
-- every other repeated write in this store follows.
--
-- This clause alone, split from three more that used to ride in the same
-- ALTER (rule 106): see 0045_entity_former_handle_width and the two
-- 0045_entity_former_handle_key_* files for the rest of what this comment
-- used to describe in one statement.
ALTER TABLE entity_former_handle ADD COLUMN ordinal INT NOT NULL DEFAULT 1;
